### ISSUE TITLE
Search canton by zipcode

### ISSUE THREAD

**Issue by Floriferous** [stefanzweifel/js-swiss-cantons#77]
Would be great to have that feature on this package as well, like in the PHP version :)

**Comment by Floriferous** [comment]
Isn't that an issue in the PHP package as well anyways? We're planning to use it server-side, so not a big issue. 

But if zipcode search is properly isolated from the rest of the code, people can decide whether or not they import it ?

**Comment by stefanzweifel** [comment]
Sure, when you're using it server-side there isn't a big-bundle-size problem 😄 

We could add a `ZipcodeSearch.js` class (similar to the [PHP version](https://github.com/stefanzweifel/php-swiss-cantons/blob/master/src/ZipcodeSearch.php)) which will not be imported into the `CantonManager.js`. 
The consumer would then be responsible for importing it correctly.

**Comment by Floriferous** [comment]
Alright I'm taking care of it.

**Comment by Floriferous** [comment]
I normalized the array of zipcodes to improve search speed, but I noticed some zipcodes are duplicate, and the city names have numbers added to them such as Lausanne:

```json
 {
   "city_name": "Lausanne 25",
   "zipcode": 1000,
   "community_name": "Lausanne",
   "canton": "VD"
 },
 {
   "city_name": "Lausanne 26",
   "zipcode": 1000,
   "community_name": "Lausanne",
   "canton": "VD"
 },
 {
   "city_name": "Lausanne 27",
   "zipcode": 1000,
   "community_name": "Lausanne",
   "canton": "VD"
 },
```

Does that have any meaning? Or can I clean it up?

**Comment by stefanzweifel** [comment]
The zipcode data set is coming from cadastre.ch. 
Unfortunately those city with numbers are valid and actually exists. I would like to keep them in the data set of the package.
